### ISSUE TITLE
Mock client for testing

### ISSUE THREAD

**Issue by thecheatah** [vapor/apns#16]
Please add a test configuration that will store messages in memory so that the sent messages can be inspected within a test case.

**Comment by madsodgaard** [comment]
Here is what I am using if anyone needs a reference:
```swift
private class TestableAPNSwiftClient: APNSwiftClient {
    struct TestNotification: APNSwiftNotification {
        var aps: APNSwiftPayload
    }
    
    enum TestError: Error {
        case failedToDecodeNotification
    }
    
    private(set) var notifications = [(APNSwiftPayload, String)]()
    
    var logger: Logger?
    var eventLoop: EventLoop
    
    init(eventLoop: EventLoop) {
        self.logger = nil
        self.eventLoop = eventLoop
    }
    
    func send(
        rawBytes payload: ByteBuffer,
        pushType: APNSwiftConnection.PushType,
        to deviceToken: String,
        expiration: Date?,
        priority: Int?,
        collapseIdentifier: String?,
        topic: String?,
        logger: Logger?,
        apnsID: UUID?
    ) -> EventLoopFuture<Void> {
        do {
            let decodedPayload = try JSONDecoder().decode(TestNotification.self, from: payload)
            notifications.append((decodedPayload.aps, deviceToken))
            return eventLoop.future()
        } catch {
            return eventLoop.future(error: TestError.failedToDecodeNotification)
        }
    }
}
```

**Comment by corysullivan** [comment]
@madsodgaard Thanks for sharing. How do you use this? Are you checking the environment at the call site?

```
if app.environment == .testing {
    let client = TestableAPNSwiftClient(...)
   client.send(...)
} else {
   req.apns.send(...)
}
```

**Comment by madsodgaard** [comment]
@corysullivan I am using APNS in a service class, which takes the client as an initializer parameter. So, I haven't used it directly from a `Request` for example, you would probably need to write your own `apnsClient` variable on `Request` to replace it like that. You can see how Vapors `Client` is implemented for inspiration: https://github.com/vapor/vapor/blob/main/Sources/Vapor/Client/Application%2BClients.swift

**Comment by 0xTim** [comment]
I'm going to close this for now. Supporting an APNS protocol that would allow it to be switched out is not something we can do in a non-breaking change but something we can add in a future version. The workaround is the one @madsodgaard has provided
