### ISSUE TITLE
Jan 9

### ISSUE THREAD

**Issue by tierracero** [vapor/apns#30]
### Describe the bug

Hi i had the push notification  working well on the server.  thou I noticed it stoped working 

Since the update of jan 9 I have not been able to get a push from the server how ever I a am able to get a push from my Mac.

 its the same code  but for some reason it docent work.

I think the problem is in APNSwift 2.2.0 an above 

Thank you in advanced, if you need more data im happy to help

### Environment

Ubunto 18.04

**Comment by tierracero** [comment]
the log in my local mac
![image](https://user-images.githubusercontent.com/23512041/107731373-74d91500-6cbb-11eb-89a7-529bedc3633a.png)

the log in server
![image](https://user-images.githubusercontent.com/23512041/107731404-828e9a80-6cbb-11eb-9e28-fb1c151ccee0.png)

**Comment by kylebrowning** [comment]
Closing this issue as steals, please update to the latest vapor/apns and if the issue persists, feel free to re-open
