### ISSUE TITLE
Support for sending PushNotifications via ProxyServer

### ISSUE THREAD

**Issue by SupaBasti** [vapor/apns#34]
right now, APNSwiftConnection does not support to configure any Proxy-Server.

I would expect to consider the configuration from my configure.swift, e.g.:
app.http.client.configuration.proxy = .some(.server(host: "localhost", port: 3128))

**Comment by kylebrowning** [comment]
I believe this is an issue upstream first, with https://github.com/kylebrowning/APNSwift/issues/104

**Comment by kylebrowning** [comment]
Closing since this is resolved in upstream

**Comment by SupaBasti** [comment]
awesome. Thanks a lot!

**Comment by kylebrowning** [comment]
Did it work @SupaBasti ?

**Comment by SupaBasti** [comment]
couldn't check it out yet, but from code it looks promising
