### ISSUE TITLE
Update to 4.0.0-beta.2 not working

### ISSUE THREAD

**Issue by Urkman** [vapor/apns#50]
### Describe the bug

Update from 3.0.0 to 4.0.0-beta.2 ist not working for me.
As soon as I update the packe I get this error:

multiple products named 'APNS' in: 'apns', 'apnswift'
multiple targets named 'APNS' in: 'apns', 'apnswift'; consider using the `moduleAliases` parameter in manifest to provide unique names

The apns Package is the only apns package in my project...

### To Reproduce

Add Version 3.0.0 to a package:
.package(url: "https://github.com/vapor/apns.git", from: "3.0.0")

After this update to 4.0.0:
.package(url: "https://github.com/vapor/apns.git", from: "4.0.0-beta.2"),

### Expected behavior
Project builds

### Environment

* Vapor Framework version: 4.67.5
* Vapor Toolbox version:
* OS version: MacOS 13.2

**Comment by kylebrowning** [comment]
@Urkman rather than using `from`, can you use `exact` I suspect that SPM is pulling in beta.3 from APNS which vapor/apns hasn't been updated for yet.

**Comment by fruitcoder** [comment]
Since APNSwift restructured the packages and names I think @Gerzer's solution with renaming the package is the best solution
