### ISSUE TITLE
APNS package not found

### ISSUE THREAD

**Issue by nicolassrod** [vapor/apns#53]
### Describe the bug
When I tried to use the package from a clean project I get this error
`product 'APNS' required by package 'hello' target 'AppTests' not found in package 'apns'.`

### To Reproduce
I am using steam project generator 4.83.1, just use apns package

```swift
// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
       .macOS(.v13)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.83.1"),
        .package(url: "https://github.com/vapor/apns.git", from: "4.0.0"),
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "APNS", package: "apns"),
            ]
        ),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),

            // Workaround for https://github.com/apple/swift-package-manager/issues/6940
            .product(name: "Vapor", package: "vapor"),
            .product(name: "APNS", package: "apns"),
        ])
    ]
)
```

### Environment
* Vapor Framework version:  4.86.2
* Vapor Toolbox version:  18.7.4
* OS version: macOS 14.1.1

**Comment by vzsg** [comment]
In the latest version (v4), the target of this package has been renamed from ~`APNS`~ to `VaporAPNS`, hence the error you're getting. Change your dependency declarations in both the app and the test targets to:

```swift
.product(name: "VaporAPNS", package: "apns"),
```

...and the error should go away.

**Comment by nicolassrod** [comment]
Yes, that worked, I think I think you will have to update the documentation, according to that we have to use a version that does not exist (5.0.0)
https://docs.vapor.codes/advanced/apns/

**Comment by 0xTim** [comment]
Resolved with https://github.com/vapor/docs/pull/943
