### ISSUE TITLE
Unable to Instantiate APNSClientConfiguration with tls certificate as in doc

### ISSUE THREAD

**Issue by ladiesman218** [vapor/apns#55]
According to documentation https://docs.vapor.codes/advanced/apns/#configuration
<img width="800" alt="image" src="https://github.com/vapor/apns/assets/7885834/7c8724a6-6109-41ad-a13e-66023ba4a466">

But this cause errors in Xcode
<img width="1147" alt="image" src="https://github.com/vapor/apns/assets/7885834/0a2ebd66-5cfd-4613-b3aa-663ecc7c27d0">

And there is only one function named `tls` in `APNSClientConfiguration` struct, which looks like this:
```swift
public static func tls(
    privateKey: NIOSSLPrivateKeySource,
    certificateChain: [NIOSSLCertificateSource]
) -> Self {
    Self(method: .tls(privateKey: privateKey, certificateChain: certificateChain))
}
 ```

Is the documentation outdated?

**Comment by kylebrowning** [comment]
YEs it is, you should be able to just load the key however you want, but we removed the convenience method for loading it from disk, as that's not proper standard practice

**Comment by ladiesman218** [comment]
<img width="1218" alt="image" src="https://github.com/vapor/apns/assets/7885834/7611f71d-5ac5-4138-9a3d-2f9ec448edf3">
I don't really know how to fix this...Could u help?

**Comment by hakarim740-com-ra** [comment]
> YEs it is, you should be able to just load the key however you want, but we removed the convenience method for loading it from disk, as that's not proper standard practice
@kylebrowning

What someone with a TLS certificate do if the JWT token is not available?

**Comment by kylebrowning** [comment]
> > YEs it is, you should be able to just load the key however you want, but we removed the convenience method for loading it from disk, as that's not proper standard practice
> 
> @kylebrowning
> 
> 
> 
> What someone with a TLS certificate do if the JWT token is not available?

Load it however you want and pass it as a string.
